example/rails-4.2/config/routes.rb
Rails.application.routes.draw do
  resources :users, :only => [:index, :new, :create]

  root :to => 'users#new'
end

example/rails-4.2/app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :phone, :presence => true, :uniqueness => true
  validate :phone_plausible

  def phone_plausible
    errors.add(:phone, :invalid) if phone.present? && !Phony.plausible?(phone)
  end

  def phone=(value)
    Phony.plausible?(value) ? super(Phony.normalize(value)) : super(value)
  end

  after_create do
    ## This would send SMS instantly and slow app down...
    # UserTexter.welcome(self).deliver_now

    ## ...so let's use shiny, async ActiveJob instead
    UserTexter.welcome(self).deliver_later
  end
end

example/rails-4.2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

example/rails-4.2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order('created_at DESC, id DESC')
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_url, notice: 'User was created and SMS notification was sent. Check server log for yourself!'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :phone)
  end
end

example/rails-4.2/app/helpers/application_helper.rb
module ApplicationHelper
end

example/rails-4.2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TextrisExample</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>Textris example</h1>

<p>This simple application demonstrates the usage scenario from <%= link_to 'textris documentation', 'https://github.com/visualitypl/textris' %>. You can add new users after which the application will send SMS with welcome notification.</p>

<p>In this Rails 4.2 example, ActiveJob is used to send SMSes asynchronously. Of course, there's no backend configured by default, so job will be invoked instantly as an inline job.</p>

<%= yield %>

</body>
</html>

example/rails-4.2/app/views/user_texter/welcome.text.erb
Welcome to our system, <%= @user.name %>!

example/rails-4.2/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>

    <% if @user.errors[:name].present? %>
      <% @user.errors[:name].each do |error| %>
        <div class="field-error"><%= error %></div>
      <% end %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>

    <% if @user.errors[:phone].present? %>
      <% @user.errors[:phone].each do |error| %>
        <div class="field-error"><%= error %></div>
      <% end %>
    <% end %>  </div>
  <div class="actions">
    <%= f.submit :class => 'btn' %>
  </div>
<% end %>

example/rails-4.2/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Previously added users</h3>

<% if @users.any? %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Phone</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.phone %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>You haven't added any users yet.</p>
<% end %>


<br>

<%= link_to 'Add new user', new_user_path, :class => 'btn' %>

example/rails-4.2/app/views/users/new.html.erb
<h3>New user</h3>

<p>Fill in a new user, so that application will send SMS with welcome notification.

<%= render 'form' %>

<%= link_to 'Back', users_path, :class => 'btn' %>